In [1]:
import numpy as np

In [3]:
#주어진 벡터의 각 요소에 5를 더한 새로운 벡터를 생성하시오.

a=np.array([1,2,3,4,5])
newa=a+5
print(newa)


[ 6  7  8  9 10]


In [5]:
#주어진 벡터의 홀수 번째 요소만 추출하여 새로운 벡터를 생성하시오
a = np.array([12,21,35,48,5])
a[::2]


array([12, 35,  5])

In [6]:
#주어진 벡터에서 최댓값을 찾으시오.
a=np.array([1,22,93,64,54])

a.max()

93

In [7]:
#주어진 벡터에서 중복된 값을 제거한 새로운 벡터를 생성하시오
a=np.array([1,2,3,2,4,5,4,6])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#주어진 두 벡터 a,b의 요소를 번갈아 가면서 위치시키는 새로운 벡터를 생성하시오.
a= np.array([21,31,58])
b= np.array([24,44,67])

c = np.empty(a.size+b.size,dtype=a.dtype)

c[0::2] = a
c[1::2] = b

print(c)

[21 24 31 44 58 67]


In [11]:
#다음 두 벡터 a와 b를 더한 결과를 구하시오 (a의 마지막 값은 제외)

a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9])

c=a[:-1]+b[:]
print(c)

[ 7  9 11 13]
