In [2]:
import numpy as np

In [3]:
#다음과 같은 행렬 A를 생성하시오.

""" 행렬 A:
    [[3 5 7]
     [2 3 6]]
"""

A = np.array([[3,5,7],[2,3,6]])
print(A)

[[3 5 7]
 [2 3 6]]


In [ ]:
#다음과 같이 행렬 B가 주어졌을때, 2번째 4번째,5번째 행만을 선택하여 3*4행렬 생성하시오

B=np.array([[8,10,7,8],[2,4,5,5],[7,6,1,7]])